### ISSUE TITLE
활동인구 등록 완료 뷰

### ISSUE THREAD

**Issue by kswgit** [CartoonIsArt/eevee#47]
활동인구 등록버튼을 누르면 보일 뷰

**Comment by kswgit** [comment]
`Regulared.js`컴포넌트를 만들고 거기에 작업해주세요

**Comment by sGOM** [comment]
개발완료!

**Comment by kswgit** [comment]
1. 글씨 색 바꾸기
2. 아이콘 간격조정
3. 아이콘 삭제
4. 회칙 링크 추가
